### ISSUE TITLE
azure function部署问题

### ISSUE THREAD

**Issue by chocolatedesue** [fumiama/MoeGoe-Android#5]
另一个仓库 https://github.com/fumiama/MoeGoe 提不了issue就到这了 == 

请问下如何解决 azure function remote build 构建pyopenjtalk没有cmake的问题

我参考了 https://learn.microsoft.com/en-us/azure/azure-functions/functions-deployment-technologies  和 _https://learn.microsoft.com/en-us/azure/azure-functions/functions-reference-python?tabs=asgi%2Capplication-level&pivots=python-mode-decorators_  但没有找到解决方法， local build 好像不太适合依赖c的python package

**Comment by fumiama** [comment]
你就用的我的requirements吗？那个就是我部署的依赖，也部署成功了没啥问题。

**Comment by chocolatedesue** [comment]
指定了 openjtalk==0.3.0.dev2 就不会从源码安装了

感谢！

**Comment by fumiama** [comment]
> 指定了 openjtalk==0.3.0.dev2 就不会从源码安装了
> 
> 感谢！

哦，当时应该是还没有dev3版本😂

**Comment by chocolatedesue** [comment]
dalao还有个问题，似乎function不支持文件持久化

pyopenjtalk lazy init 在线上环境运行不了， 得先手动
```bash
func azure functionapp publish $name  --force --python --build-native-deps
```
然后cd到对应目录运行  
这一块如何处理？


错误日志 
![image](https://user-images.githubusercontent.com/91049859/235305025-ea6ecef7-683a-42fa-8dbd-f3dea63191ad.png)

**Comment by fumiama** [comment]
不会吧😂我用的就是这个啊，lazy理论上已经在安装时下载好了，不需要额外下载。

**Comment by chocolatedesue** [comment]
懂了 感谢
